version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - public
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "514:514"
      - "514:514/udp"
    networks:
      - public
    depends_on:
      - "elasticsearch"
  grafana:
    image: grafana/grafana-oss
    container_name: 'grafana'
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./configs/grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./configs/grafana/cloudguard.json:/etc/grafana/provisioning/dashboards/cloudguard.json
    networks:
      - public
    ports:
      - 3000:3000
    depends_on:
      - "elasticsearch"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  public:
    name: public

volumes:
  data01:
    driver: local
  grafana-storage:
