apiVersion: 1

datasources:
- name: Elasticsearch
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch:9200
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  database: "fluent-bit"
  jsonData:
    timeField: '@timestamp'
    esVersion: 70
    logMessageField: message
    logLevelField: severity
  
