apiVersion: 1

datasources:
- name: elasticsearch
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  database: "fluent-bit"
  logMessageField: message
  logLevelField: severity
  
